name: deploy
on:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.ref }}
env:
  AWS_REGION: ap-northeast-1
  DOMAIN_NAME: mallows.io
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - run: |
          yarn --frozen-lockfile
      - run: |
          yarn cdk deploy \
            -c domainName=${{ env.DOMAIN_NAME }} \
            -c certificateArn=${{ secrets.CERTIFICATE_ARN }} \
            -c openaiApiKey=${{ secrets.OPENAI_API_KEY }} \
            -c githubRepository=${{ github.repository }} \
            -c githubRef=${{ github.ref }} \
            --require-approval never \
            -O outputs.json
      - run: |
          VITE_API_ENDPOINT=$(cat outputs.json | jq -r '.MallowsGpt.ApiEndpoint') yarn build
      - run: |
          aws s3 sync dist s3://$(cat outputs.json | jq -r '.MallowsGpt.AppBucketName') \
            --exact-timestamps \
            --delete
      - run: |
          aws cloudfront create-invalidation \
            --distribution-id $(cat outputs.json | jq -r '.MallowsGpt.AppDistributionId') \
            --paths '/*'
